### ISSUE TITLE
Installation question

### ISSUE THREAD

**Issue by adriancampanaro** [DrudgeRajen/voyager-deployment-orchestrator#16]
Hi
To install this, do I need Voyager already in my project, or this creates the Voyager package?

Regards
Adrian

**Comment by DrudgeRajen** [comment]
Hi @adriancampanaro,

This package requires voyager. So, if you had installed voyager already then no need to install if not then this package will install it.

**Comment by DrudgeRajen** [comment]
Please open it if necessary. Closing for now.
