### ISSUE TITLE
Order of Menu Item for a bread data type is not seeded correctly

### ISSUE THREAD

**Issue by ajcastro** [DrudgeRajen/voyager-deployment-orchestrator#17]
I move the menu_item to some order, then when re-migrate my tables and run this orchestrator package, the order set for the menu_item is always in the last.

I think we need to listen on the event when the menu_item is moved up or down and saved it in the seeder.

**Comment by DrudgeRajen** [comment]
hi @ajcastro, Good catch but unfortunately voyager doesn't fire any events for menu (CRUD) so it is not possible to fix this issue currently. 

https://github.com/the-control-group/voyager/blob/1.2/src/Http/Controllers/VoyagerMenuController.php

**Comment by ajcastro** [comment]
What if we add a command something like `php artisan voyager-deployment-orchestrator:save_menu_items_order` that will create a seeder where it updates the menu_items order base from current database state of menu_items

**Comment by DrudgeRajen** [comment]
Hi @ajcastro, I like the idea. PR's welcome :)

**Comment by mjducharme** [comment]
I'm wondering if it might be better to add full blown support to sync the menus (not only the items order). If we have multiple instances of an app we usually want the menus to be synced as well. I do this right now with iseed but like the VDO approach more since I don't have to think about it.
