### ISSUE TITLE
PHP Warning:  Use of undefined constant nationalities in config file

### ISSUE THREAD

**Issue by arshohag** [DrudgeRajen/voyager-deployment-orchestrator#28]
PHP Warning:  Use of undefined constant nationalities - assumed 'nationalities' (this will throw an Error in a future version of PHP) in /var/www/html/laravel/config/voyager-deployment-orchestrator.php on line 6

always showing this warning for any artisan commands.

**Comment by DrudgeRajen** [comment]
Hi @arshohag ,
Can you please mention versions of PHP, Laravel, and Voyager?

**Comment by arshohag** [comment]
> Hi @arshohag ,
> Can you please mention versions of PHP, Laravel, and Voyager?

PHP - ^7.3
Laravel - ^6.0
Voyager - ^1.2

If I comment out the table name in configuration file then error not appearing.

**Comment by DrudgeRajen** [comment]
@arshohag This issue is not related to this package. My guess is, you tried to update the config file with the table name but forget to wrap with an apostrophe.

**Comment by arshohag** [comment]
update your documentation 

```
return [
    'tables' => [
        'users'
    ],
];
```

it is missing there

**Comment by DrudgeRajen** [comment]
Did you go through the documentation? It's on the [Readme](https://github.com/DrudgeRajen/voyager-deployment-orchestrator/blob/master/README.MD)
