### ISSUE TITLE
Deprecation Notice

### ISSUE THREAD

**Issue by igibek** [DrudgeRajen/voyager-deployment-orchestrator#29]
Laravel: __^7.0__
Composer: __1.10.5__
`composer dump-autoload` displays deprecation warning.
Message:
`Deprecation Notice: Class DrudgeRajen\VoyagerDeploymentOrchestrator\ContentManger\FileSystem located in ./vendor/drudge-rajen/voyager-deployment-orchestrator/src/ContentManager/FileSystem.php does not comply with psr-4 autoloading standard. It will not autoload anymore in Composer v2.0. in phar:///usr/local/Cellar/composer/1.10.5/bin/composer/src/Composer/Autoload/ClassMapGenerator.php:201`

**Comment by sprklinginfo** [comment]
just installed the package and saw the same Deprecation Notice. Is it fixed or not?

**Comment by oliva1337** [comment]
Just got this
ReflectionException::("Class DrudgeRajen\VoyagerDeploymentOrchestrator\ContentManger\FileSystem does not exist")
