### ISSUE TITLE
Need listen for "permission_role" table / bread

### ISSUE THREAD

**Issue by rizkiheryandi** [DrudgeRajen/voyager-deployment-orchestrator#9]
This awesome library need listen to "permission_role" table / bread

**Comment by ajcastro** [comment]
@DrudgeRajen what is the problem here? can this be elaborated please, the use-case?

**Comment by DrudgeRajen** [comment]
@rizkiheryandi  VDO populates the permission statements. So, no need to listen for the `permission_role` table.

https://github.com/DrudgeRajen/voyager-deployment-orchestrator/blob/f6ca5394f4cb6ca6fa3e7142d6b4cb0ef98ccfb6/src/ContentManager/ContentManager.php#L205-L209
